### PR TITLE
feat: cache layers on disk

### LINKED ISSUE #34: Feature request: Cache result?
I find that if I change tabs / go to Inspect / Summary it re-loads again, I'm unsure if this is intentional.

Is there a way to cache the result and only reload if there has been a change to the image? For example.. store the information but only load if the image id (sha value) has changed?

### PR DESCRIPTION
**Pull request by feloy**
Cache layers on disk
The cache size is settable, and is 100 MB by default
A cache file is deleted when the associated image is deleted

Fixes #34

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
I checkout the repository and yarn watch. Inside podman-desktop the extension is in error state.

Getting the following error 

```
Error: ENOENT: no such file or directory, scandir '~/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.layers-explorer/cache/v1'
```

**Review by jeffmaury — APPROVED** [review]
LGTM.

I'm questioning the 100MB limit as on the images that I tried, the layers are bigger. Can we set it as a part of the free space ?

**Comment by feloy** [comment]
> LGTM.
> 
> I'm questioning the 100MB limit as on the images that I tried, the layers are bigger. Can we set it as a part of the free space ?

We are not caching the complete layers, but only their metadata (files names/permissions/sizes/etc). For big images I have tested, the cache is about 300kb. This leaves room for at least 300 cached images

**Comment by jeffmaury** [comment]
> > LGTM.
> > I'm questioning the 100MB limit as on the images that I tried, the layers are bigger. Can we set it as a part of the free space ?
> 
> We are not caching the complete layers, but only their metadata (files names/permissions/sizes/etc). For big images I have tested, the cache is about 300kb. This leaves room for at least 300 cached images

So why my cache is empty (a single empty sha256 file) ?

**Comment by feloy** [comment]
> > > LGTM.
> > > I'm questioning the 100MB limit as on the images that I tried, the layers are bigger. Can we set it as a part of the free space ?
> > 
> > 
> > We are not caching the complete layers, but only their metadata (files names/permissions/sizes/etc). For big images I have tested, the cache is about 300kb. This leaves room for at least 300 cached images
> 
> So why my cache is empty (a single empty sha256 file) ?

@jeffmaury The filenames were `sha256:123...`, but colons are reserved chars on Windows. The latest commit should fix the problem.

**Pull request merged**
